"""Changed tasks table

Revision ID: 59bf6ee022a8
Revises: 
Create Date: 2025-03-15 14:54:18.957386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59bf6ee022a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knownfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('encoding', postgresql.ARRAY(sa.FLOAT()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knownfaces_first_name'), 'knownfaces', ['first_name'], unique=False)
    op.create_index(op.f('ix_knownfaces_id'), 'knownfaces', ['id'], unique=False)
    op.create_index(op.f('ix_knownfaces_last_name'), 'knownfaces', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knownfaces_last_name'), table_name='knownfaces')
    op.drop_index(op.f('ix_knownfaces_id'), table_name='knownfaces')
    op.drop_index(op.f('ix_knownfaces_first_name'), table_name='knownfaces')
    op.drop_table('knownfaces')
    # ### end Alembic commands ###
